openapi: '3.0.3'
info:
  title: gardner samples collecting service
  version: '1.0.0'
paths:
  /next-sample:
    get:
      summary: get minutes until next sample
      responses:
        '200':
          description: minutes until next sample
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Minutes'

  /sample:
    post:
      summary: post a sample
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      responses:
        '201':
          description: sample was saved

  /samples:
    post:
      summary: post a sample
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                boards:
                  type: array
                  items:
                    $ref: '#/components/schemas/Board'
      responses:
        '201':
          description: sample was saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Minutes'

components:
  schemas:
    Sample:
      type: object
      properties:
        boardId:
          type: number
        sensorId:
          type: number
        reading:
          type: number
    Board:
      type: object
      properties:
        id:
          type: number
        readings:
          type: array
          items:
            type: number
    Minutes:
      type: object
      properties:
        minutes:
          type: number
